/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package framecon;

import DuLieu.DbUtils;
import DuLieu.DocGiaData;
import DuLieu.Regex;
import Object.DocGia;
import java.awt.Color;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author trung
 */
public class pane2 extends javax.swing.JPanel {

    /**
     * Creates new form pane2
     */
    DocGiaData dgdt=new DocGiaData();
    public pane2() {
        initComponents();
        this.setBackground(Color.CYAN);
        CapNhat();
        SetButtom();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        bt_themdg = new javax.swing.JButton();
        bt_updg = new javax.swing.JButton();
        bt_xoadg = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_madg = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_tendg = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_diachi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_phone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_matkhaudg = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabledocgia = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        txt_tim = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Chưc Năng"));

        jButton2.setBackground(new java.awt.Color(0, 153, 153));
        jButton2.setIcon(new javax.swing.ImageIcon("E:\\imgg\\nhapdocgia.png")); // NOI18N
        jButton2.setText("Nhập Độc Giả");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        bt_themdg.setBackground(new java.awt.Color(0, 153, 153));
        bt_themdg.setIcon(new javax.swing.ImageIcon("E:\\imgg\\themdocgia.png")); // NOI18N
        bt_themdg.setText("Thêm Độc Giả");
        bt_themdg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_themdgActionPerformed(evt);
            }
        });

        bt_updg.setBackground(new java.awt.Color(0, 153, 153));
        bt_updg.setIcon(new javax.swing.ImageIcon("E:\\imgg\\updatedocgia.png")); // NOI18N
        bt_updg.setText("Update Độc Giả");
        bt_updg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_updgActionPerformed(evt);
            }
        });

        bt_xoadg.setBackground(new java.awt.Color(0, 153, 153));
        bt_xoadg.setIcon(new javax.swing.ImageIcon("E:\\imgg\\xoadocgia.png")); // NOI18N
        bt_xoadg.setText("Xóa Độc Giả");
        bt_xoadg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_xoadgActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bt_xoadg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_updg, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(bt_themdg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_themdg, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_updg, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_xoadg, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Nhập Thông Tin"));

        jLabel1.setText("Ma DG");

        jLabel2.setText("Tên DG");

        jLabel3.setText("Địa Chỉ DG");

        jLabel4.setText("Phone  DG");

        jLabel5.setText("Email  DG");

        jLabel6.setText("Mat Khau");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(13, 13, 13))
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_email, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addComponent(txt_tendg)
                            .addComponent(txt_matkhaudg, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_madg)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_diachi, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_madg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_matkhaudg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_tendg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_diachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(22, 22, 22))
        );

        tabledocgia.setBackground(new java.awt.Color(255, 255, 153));
        tabledocgia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabledocgia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabledocgiaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabledocgia);

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("E:\\imgg\\searchdocgia.png")); // NOI18N
        jButton1.setText("Tìm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txt_tim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_timKeyReleased(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon("E:\\imgg\\anhthe1.png")); // NOI18N
        jLabel7.setText("jLabel7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(txt_tim, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 811, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tim, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
         //ham hien thi cap nhat lai toan bo thong tin doc gia
    public void CapNhat(){
        ResultSet rs=dgdt.HienThiDG();
        tabledocgia.setModel(DbUtils.resultSetToTableModel(rs));
    }
    //ham xet hien thi cua cac buttom
    public void SetButtom(){
        bt_themdg.setEnabled(false);
        bt_updg.setEnabled(false);
        bt_xoadg.setEnabled(false);
    }
    private void bt_themdgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_themdgActionPerformed
        try{
        String ma=txt_madg.getText();
        String matkhau=txt_matkhaudg.getText();
        String tendg=txt_tendg.getText();
        String diachi=txt_diachi.getText();
        String phone=txt_phone.getText();
        String email=txt_email.getText();
        DocGia dg=new DocGia(ma, matkhau, tendg, diachi, phone, email);
        if(!Regex.validate(email))
            JOptionPane.showMessageDialog(this, "Email khong hop le");
        if(!Regex.checkphone(phone))
            JOptionPane.showMessageDialog(this, "Phone Khong Hop Le");
        if(Regex.validate(email) && Regex.checkphone(phone)){
            if(dgdt.checkmadg(ma)){
        boolean f=dgdt.ThemDG(dg);
        if(f)
            JOptionPane.showMessageDialog(this, "Them Doc Gia Thanh Cong");
            }
        else
            JOptionPane.showMessageDialog(this, "Trung Ma");
        }
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        }
        CapNhat();
    }//GEN-LAST:event_bt_themdgActionPerformed

    private void bt_updgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_updgActionPerformed
        try{
        String ma=txt_madg.getText();
        String matkhau=txt_matkhaudg.getText();
        String tendg=txt_tendg.getText();
        String diachi=txt_diachi.getText();
        String phone=txt_phone.getText();
        String email=txt_email.getText();
        DocGia dg=new DocGia(ma, matkhau, tendg, diachi, phone, email);
        boolean f=dgdt.UpdateDG(dg);
        if(f)
            JOptionPane.showMessageDialog(this, "Chinh Sua Doc Gia Thanh Cong");
        else
            JOptionPane.showMessageDialog(this, "Chinh Sua doc Gia That Bai");
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        }
        CapNhat();
    }//GEN-LAST:event_bt_updgActionPerformed

    private void tabledocgiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabledocgiaMouseClicked
        int row = tabledocgia.getSelectedRow();
        if (row != -1) {
            txt_madg.setText(tabledocgia.getValueAt(row, 0).toString());
            txt_matkhaudg.setText(tabledocgia.getValueAt(row, 1).toString());
            txt_tendg.setText(tabledocgia.getValueAt(row, 2).toString());
            txt_diachi.setText(tabledocgia.getValueAt(row, 3).toString());
            txt_phone.setText(tabledocgia.getValueAt(row, 4).toString());
            txt_email.setText(tabledocgia.getValueAt(row, 5).toString());
        }
        SetButtom();
        bt_updg.setEnabled(true);
        bt_xoadg.setEnabled(true);
    }//GEN-LAST:event_tabledocgiaMouseClicked

    private void bt_xoadgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_xoadgActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Are you sure?", "WARNING",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            String ma = txt_madg.getText();
            boolean f = dgdt.XoaDG(ma);
            if (f) {
                JOptionPane.showMessageDialog(this, "Xoa Thanh Cong");
            } else {
                JOptionPane.showMessageDialog(this, "Xoa That Bai");
            }
        } else {
        }
        CapNhat();
    }//GEN-LAST:event_bt_xoadgActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       txt_diachi.setText("");
       txt_email.setText("");
       txt_madg.setText("");
       txt_matkhaudg.setText("");
       txt_phone.setText("");
       txt_tendg.setText("");
       SetButtom();
       bt_themdg.setEnabled(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt_timKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_timKeyReleased
        String tim=txt_tim.getText();
        
        ResultSet rs=dgdt.timKiem(tim);
        tabledocgia.setModel(DbUtils.resultSetToTableModel(rs));
    }//GEN-LAST:event_txt_timKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         String tim=txt_tim.getText();
        
        ResultSet rs=dgdt.timKiem(tim);
        tabledocgia.setModel(DbUtils.resultSetToTableModel(rs));
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_themdg;
    private javax.swing.JButton bt_updg;
    private javax.swing.JButton bt_xoadg;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabledocgia;
    private javax.swing.JTextField txt_diachi;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_madg;
    private javax.swing.JTextField txt_matkhaudg;
    private javax.swing.JTextField txt_phone;
    private javax.swing.JTextField txt_tendg;
    private javax.swing.JTextField txt_tim;
    // End of variables declaration//GEN-END:variables
}
